In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(digits.data, digits.target , test_size=0.3)

In [4]:
reg = LogisticRegression(max_iter=4000)
reg.fit(x_train,y_train)
reg.score(x_test,y_test)

0.9703703703703703

In [5]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)                     # 3 pair of train-test datasets will be created.-
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [6]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):    # It is an exapmle dataset[1,2,3...] created not the real one.
    print(train_index , test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [8]:
def get_score(model , x_train ,x_test ,y_train ,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [10]:
from sklearn.model_selection import StratifiedKFold          # Real operation starts here with digits dataset .
folds = StratifiedKFold(n_splits=3)

In [21]:
scores_reg = []
scores_svm = []
scores_rf = []

for train_index , test_index in kf.split(digits.data):
    x_train , x_test , y_train , y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index],digits.target[test_index]

    scores_reg.append(get_score(LogisticRegression(max_iter=5000),x_train ,x_test ,y_train ,y_test))
    scores_svm.append(get_score(SVC(),x_train ,x_test ,y_train ,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),x_train ,x_test ,y_train ,y_test))

In [22]:
scores_reg

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [23]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [28]:
scores_rf

[0.9265442404006677, 0.9565943238731218, 0.9198664440734557]

In [25]:
from sklearn.model_selection import cross_val_score

In [27]:
cross_val_score(LogisticRegression(max_iter=5000), digits.data,digits.target)   # To avoid the above code[21] use this method

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [31]:
cross_val_score(SVC(), digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [32]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data,digits.target)

array([0.92777778, 0.9       , 0.94986072, 0.96657382, 0.91922006])

In [34]:
cross_val_score(RandomForestClassifier(n_estimators=15), digits.data,digits.target)  #Comparing same algo with diff paramater can also be done using this method cross_val_score.

array([0.92222222, 0.83888889, 0.95543175, 0.95264624, 0.91086351])

In [35]:
cross_val_score(RandomForestClassifier(n_estimators=5), digits.data,digits.target)

array([0.85277778, 0.81388889, 0.90807799, 0.88579387, 0.8356546 ])